OgrenciNotMVC/OgrenciNotMVC/Controllers/NotlarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OgrenciNotMVC.Models;
using OgrenciNotMVC.Models.EntitiyFramework;


namespace OgrenciNotMVC.Controllers
{
    public class NotlarController : Controller
    {
        // GET: Notlar
        DbMvcOkulEntities db = new DbMvcOkulEntities();
        public ActionResult Index()
        {
            var notlar = db.TblNotlar.ToList();
            return View(notlar);
        }
        [HttpGet]
        public ActionResult YeniSinav()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniSinav(TblNotlar p)
        {
            db.TblNotlar.Add(p);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public ActionResult NotGetir(int id)
        {
            var guncellenecekNot = db.TblNotlar.Find(id);
            return View(nameof(NotGetir), guncellenecekNot);
        }
        [HttpPost]
        public ActionResult NotGetir(TblNotlar p, int proje, Class1 model, int sinav1 = 0, int sinav2 = 0, int sinav3 = 0)
        {
            if (model.islem == "Hesapla")
            {
                //islem1
                decimal ortalama = (sinav1 + sinav2 + sinav3 + proje) / 4;
                // Durumu belirleme işlemi
                p.Durum = ortalama > 50 ? "Geçti" : "Kaldı";
                ViewBag.ort = ortalama;
                ViewBag.durm = p.Durum;
                //p.Durum = ortalama > 50 ? "True" : "False";

            }
            else if (model.islem == "NotGuncelle")
            {
                //islem2
                var notlar = db.TblNotlar.Find(p.NotID);
                notlar.Sinav1 = p.Sinav1;
                notlar.Sinav2 = p.Sinav2;
                notlar.Sinav3 = p.Sinav3;
                notlar.Proje = p.Proje;
                notlar.Ortalama = p.Ortalama;

                // Burada Durum değerini güncellemeyi unutmayın
                notlar.Durum = p.Ortalama > 50 ? "Geçti" : "Kaldı";
                ViewBag.durm = notlar.Durum;
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

    }
}

OgrenciNotMVC/OgrenciNotMVC/Views/Notlar/Index.cshtml
@using OgrenciNotMVC.Models.EntitiyFramework
@model List<TblNotlar>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>Not ID</th>
        <th>Ders ID</th>
        <th>Öğrenci ID</th>
        <th>Sınav 1</th>
        <th>Sınav 2</th>
        <th>Sınav 3</th>
        <th>Proje</th>
        <th>Ortalama</th>
        <th>Durum</th>
        <th>Güncelle</th>
    </tr>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.NotID</td>
                <td>@item.DersID</td>
                <td>@item.OgrID</td>
                <td>@item.Sinav1</td>
                <td>@item.Sinav2</td>
                <td>@item.Sinav3</td>
                <td>@item.Proje</td>
                <td>@item.Ortalama</td>
                <td>@item.Durum</td>
                <td>
                    <a href="/Notlar/NotGetir/@item.NotID"class="btn btn-warning">Güncelle</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a href="/Notlar/YeniSinav/" class="btn btn-primary">Yeni Sınav Girişi</a>

OgrenciNotMVC/OgrenciNotMVC/Views/Notlar/NotGetir.cshtml
@model OgrenciNotMVC.Models.EntitiyFramework.TblNotlar
@{
    ViewBag.Title = "NotGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("NotGetir", "Notlar", FormMethod.Post))
{
    <div class="form-group">
        <label>Öğrenci Ad</label>
        @Html.TextBoxFor(k => k.OgrID, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Sınav 1</label>
        @Html.TextBoxFor(k => k.Sinav1, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Sınav 2</label>
        @Html.TextBoxFor(k => k.Sinav2, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Sınav 3</label>
        @Html.TextBoxFor(k => k.Sinav3, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Proje</label>
        @Html.TextBoxFor(k => k.Proje, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Ortalama</label>
        @Html.TextBoxFor(k => k.Ortalama, new { @Value = @ViewBag.ort, @class = "form-control", @readonly = "readonly" })
    </div>
    <div class="form-group">
        <label>Durum</label>
        @Html.TextBoxFor(k => k.Durum, new { @Value = @ViewBag.durm, @class = "form-control" })
    </div>

    @Html.HiddenFor(k => k.NotID)
    <div style="margin-top:15px">
        <button type="submit" name="islem" value="Hesapla" class="btn btn-primary">Ortalama Hesapla</button>
        <br />
        <button type="submit" name="islem" value="NotGuncelle" class="btn btn-info" style="margin-top:15px">Güncelle</button>
    </div>
}

OgrenciNotMVC/OgrenciNotMVC/Views/Notlar/YeniSinav.cshtml
@{
    ViewBag.Title = "YeniSinav";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <form method="post" class="form-group">
        <div>
            <label>Öğrenci ID</label>
            <input type="text" class="form-control" name="OgrID" />
        </div>
        <div style="margin-top:10px">
            <label>Ders ID</label>
            <input type="text" class="form-control" name="DersID" />
        </div>
        <div style="margin-top:10px">
            <label>Sınav 1</label>
            <input type="text" class="form-control" name="Sinav1" />
        </div>
        <div style="margin-top:10px">
            <label>Sınav 2</label>
            <input type="text" class="form-control" name="Sinav2" />
        </div>
        <div style="margin-top:10px">
            <label>Sınav 3</label>
            <input type="text" class="form-control" name="Sinav3" />
        </div>
        <div style="margin-top:10px">
            <label>Proje</label>
            <input type="text" class="form-control" name="Proje" />
        </div>
        <div style="margin-top:10px">
            <label>Ortalama</label>
            <input type="text" class="form-control" name="Ortalama" />
        </div>
        <div style="margin-top:10px">
            <label>Durum</label>
            <input type="text" class="form-control" name="Durum" />
        </div>
        <div style="margin-top:10px">
            <button class="btn btn-primary">Sınav Ekle</button>
        </div>
    </form>
</div>