OgrenciNotMVC/OgrenciNotMVC/Controllers/KuluplerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OgrenciNotMVC.Models.EntitiyFramework;

namespace OgrenciNotMVC.Controllers
{
    public class KuluplerController : Controller
    {
        // GET: Kulupler
        DbMvcOkulEntities db = new DbMvcOkulEntities();
        public ActionResult Index()
        {
            var kulupler = db.TblKulupler.ToList();
            return View(kulupler);
        }

        [HttpGet]
        public ActionResult YeniKulup()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniKulup(TblKulupler p)
        {
            db.TblKulupler.Add(p);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public ActionResult Sil(int id)
        {
            var silinecekKulup = db.TblKulupler.Find(id);
            db.TblKulupler.Remove(silinecekKulup);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public ActionResult KulupGetir(int id)
        {
            var guncellenecekKulup = db.TblKulupler.Find(id);
            return View(nameof(KulupGetir), guncellenecekKulup);
        }
        public ActionResult Guncelle(TblKulupler p)
        {
            var kulup = db.TblKulupler.Find(p.KulupID);
            kulup.KulupAd = p.KulupAd;
            kulup.KulupKontenjan = p.KulupKontenjan;
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

OgrenciNotMVC/OgrenciNotMVC/Views/Kulupler/Index.cshtml
@using OgrenciNotMVC.Models.EntitiyFramework
@model List<TblKulupler>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>Kulüp ID</th>
        <th>Kulüp Adı</th>
        <th>Kulüp Kontenjen</th>
        <th>İşlemler</th>
    </tr>
    <tbody>
        @foreach (var kulup in Model)
        {
            <tr>
                <td>@kulup.KulupID.ToString()</td>
                <td>@kulup.KulupAd.ToString()</td>
                <td>@kulup.KulupKontenjan.ToString()</td>
                <td>
                    <a href="/Kulupler/Sil/@kulup.KulupID" class="btn btn-danger">Sil</a>
                    <a href="/Kulupler/KulupGetir/@kulup.KulupID" style="margin-left:15px" class="btn btn-success">Güncelle</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a href="/Kulupler/YeniKulup/" class="btn btn-primary">Yeni Kulüp Kaydı</a>

OgrenciNotMVC/OgrenciNotMVC/Views/Kulupler/KulupGetir.cshtml
@model OgrenciNotMVC.Models.EntitiyFramework.TblKulupler
@{
    ViewBag.Title = "KulupGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Guncelle", "Kulupler", FormMethod.Post))
{
    <div class="form-group">
        <label>Kulüp Adı</label>
        @Html.TextBoxFor(k => k.KulupAd, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Kulüp Kontenjanı</label>
        @Html.TextBoxFor(k => k.KulupKontenjan, new { @class = "form-control" })
    </div>
    @Html.HiddenFor(k => k.KulupID)
    <div style="margin-top:15px">
        <button class="btn btn-info">Güncelle</button>
    </div>
}

OgrenciNotMVC/OgrenciNotMVC/Views/Kulupler/YeniKulup.cshtml
@{
    ViewBag.Title = "YeniKulup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" class="form-group">

    <div>
        <label>Kulüp Adı</label>
        <input type="text" class="form-control" name="KulupAd" />
    </div>

    <div>
        <label>Kulüp Kontenjanı</label>
        <input type="text" class="form-control" name="KulupKontenjan" />
    </div>

    <div style="margin-top:10px">
        <button class="btn btn-primary">Kulüp Ekle</button>
    </div>

</form>