OgrenciNotMVC/OgrenciNotMVC/Controllers/OgrenciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OgrenciNotMVC.Models.EntitiyFramework;

namespace OgrenciNotMVC.Controllers
{
    public class OgrenciController : Controller
    {
        // GET: Ogrenci 
        DbMvcOkulEntities db = new DbMvcOkulEntities();
        public ActionResult Index()
        {
            var ogrenci = db.TblOgrenciler.ToList();
            return View(ogrenci);
        }

        [HttpGet]
        public ActionResult OgrenciEkle()
        {
            List<SelectListItem> degerler = (from x in db.TblKulupler.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = x.KulupAd,
                                                 Value = x.KulupID.ToString()
                                             }).ToList();
            ViewBag.deger = degerler;
            return View();
        }

        [HttpPost]
        public ActionResult OgrenciEkle(TblOgrenciler p)
        {
            var kulup = db.TblKulupler.Where(k => k.KulupID == p.TblKulupler.KulupID).FirstOrDefault();
            p.TblKulupler = kulup;
            db.TblOgrenciler.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {
            var silinecekOgrenci = db.TblOgrenciler.Find(id);

            var notlar = db.TblNotlar.Where(n => n.OgrID == id);
            db.TblNotlar.RemoveRange(notlar);

            db.TblOgrenciler.Remove(silinecekOgrenci);

            db.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public ActionResult OgrenciGetir(int id)
        {
            var guncellenecekOgrenci = db.TblOgrenciler.Find(id);

            List<SelectListItem> degerler = (from x in db.TblKulupler.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = x.KulupAd,
                                                 Value = x.KulupID.ToString()
                                             }).ToList();
            ViewBag.deger = degerler;

            return View(nameof(OgrenciGetir), guncellenecekOgrenci);
        }
        public ActionResult Guncelle(TblOgrenciler p)
        {
            var ogrenci = db.TblOgrenciler.Find(p.OgrenciID);
            ogrenci.OgrAd = p.OgrAd;
            ogrenci.OgrSoyad = p.OgrSoyad;
            ogrenci.OgrFotograf = p.OgrFotograf;
            ogrenci.OgrCinsiyet = p.OgrCinsiyet;
            ogrenci.OgrKulup = p.OgrKulup;
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

OgrenciNotMVC/OgrenciNotMVC/Views/Ogrenci/Index.cshtml
@using OgrenciNotMVC.Models.EntitiyFramework
@model List<TblOgrenciler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<table class="table table-bordered">
    <tr>
        <th>Öğrenci ID</th>
        <th>Öğrenci Ad</th>
        <th>Öğrenci SoyAd</th>
        <th>Öğrenci Kulüp</th>
        <th>Öğrenci Cinsiyet</th>
        <th>İşlemler</th>
    </tr>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.OgrenciID</td>
                <td>@item.OgrAd</td>
                <td>@item.OgrSoyad</td>
                <td>@item.TblKulupler.KulupAd</td>
                <td>@item.OgrCinsiyet</td>
                <td>
                    <a href="/Ogrenci/Sil/@item.OgrenciID" class="btn btn-danger">Sil</a>
                    <a href="/Ogrenci/OgrenciGetir/@item.OgrenciID" class="btn btn-success" style="margin-left:15px">Güncelle</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a href="/Ogrenci/OgrenciEkle/" class="btn btn-primary">Yeni Öğrenci Kaydı</a>

OgrenciNotMVC/OgrenciNotMVC/Views/Ogrenci/OgrenciEkle.cshtml
@model OgrenciNotMVC.Models.EntitiyFramework.TblOgrenciler
@{
    ViewBag.Title = "OgrenciEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <form method="post" class="form-group">
        <div>
            <label>Öğrenci Adı</label>
            <input type="text" class="form-control" name="OgrAd" />
        </div>
        <div style="margin-top:10px">
            <label>Öğrenci Soyadı</label>
            <input type="text" class="form-control" name="OgrSoyad" />
        </div>
        <div style="margin-top:10px">
            <label>Öğrenci Fotoğrafı</label>
            <input type="text" class="form-control" name="OgrFotograf" />
        </div>
        <div style="margin-top:10px">
            <label>Öğrenci Cinsiyeti</label>
            <input type="text" class="form-control" name="OgrCinsiyet" />
        </div>
        <div style="margin-top:10px">
            <label>Öğrenci Kulübü</label>
            @Html.DropDownListFor(x => x.TblKulupler.KulupID, (List<SelectListItem>)ViewBag.deger,
           new { @class = "form-control" })
        </div>
        <div style="margin-top:10px">
            <button class="btn btn-primary">Öğrenci Ekle</button>
        </div>
    </form>
</div>

OgrenciNotMVC/OgrenciNotMVC/Views/Ogrenci/OgrenciGetir.cshtml
@model OgrenciNotMVC.Models.EntitiyFramework.TblOgrenciler
@{
    ViewBag.Title = "OgrenciGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Guncelle", "Ogrenci", FormMethod.Post))
{
    <div class="form-group">
        <label>Ad</label>
        @Html.TextBoxFor(k => k.OgrAd, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Soyad</label>
        @Html.TextBoxFor(k => k.OgrSoyad, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Fotoğraf</label>
        @Html.TextBoxFor(k => k.OgrFotograf, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Kulüp</label>
        @Html.TextBoxFor(k => k.OgrKulup, new { @class = "form-control" })
        @*@Html.DropDownListFor(x => x.TblKulupler.KulupID, (List<SelectListItem>)ViewBag.deger,
          new { @class = "form-control" })*@
    </div>
    <div class="form-group">
        <label>Cinsiyet</label>
        @Html.TextBoxFor(k => k.OgrCinsiyet, new { @class = "form-control" })
    </div>
    @Html.HiddenFor(k => k.OgrenciID)
    <div style="margin-top:15px">
        <button class="btn btn-info">Güncelle</button>
    </div>
}